import React, { createContext, useContext, useState } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Sidebar / Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.kpis': 'KPIs & Analyses',
    'nav.invoices': 'Factures & OCR',
    'nav.stores': 'Magasins',
    'nav.articles': 'Articles',
    'nav.prices': 'Comparateur Prix',
    'nav.consumption': 'Consommation & Alertes',
    'nav.budgets': 'Budgets',
    'nav.settings': 'Paramètres',
    'nav.logout': 'Se déconnecter',
    'role.admin': 'Administrateur',
    'role.family': 'Membre Famille',
    'role.user': 'Utilisateur Simple',
    'app.init': 'Initialisation de FinTrack...',
    'dash.welcome': 'Bonjour',
    'dash.welcome.desc': "Voici l'état actuel de vos dépenses et analyses financières.",
    'dash.overview': 'Aperçu des dépenses',
    'dash.kpi.today.footer': 'Dépenses du jour',
    'dash.kpi.week.footer': 'Dépenses de la semaine',
    'dash.kpi.month.footer': 'factures mensuelles',
    'dash.kpi.year.footer': 'Cumul annuel',
    'dash.kpi.cumulative.footer': 'Total historique',
    'dash.items.title': 'Articles Achetés',
    'dash.items.footer': 'factures au total dans FinTrack',
    'dash.savings.footer': 'Économie potentielle cumulée cette année en achetant au prix minimum constaté !',
    'dash.category.breakdown': 'Répartition par Catégorie',
    'dash.store.breakdown': 'Dépenses par Magasin',
    'dash.recent.no_purchases': 'Aucun achat récent.',
    'dash.recent.no_invoices': 'Aucune facture récente.',
    'dash.loading': 'Chargement du tableau de bord...',
    'dash.total': 'Total',
    'dash.no_data': 'Aucune donnée à afficher.',

    // Auth / Login
    'auth.title.login': 'Connexion à FinTrack',
    'auth.title.register': 'Créer un compte FinTrack',
    'auth.subtitle.login': 'Connectez-vous pour gérer vos dépenses',
    'auth.subtitle.register': 'Créez un compte famille ou utilisateur',
    'auth.label.name': 'Nom complet *',
    'auth.label.email': 'Email *',
    'auth.label.password': 'Mot de passe *',
    'auth.btn.login': 'Se connecter',
    'auth.btn.register': 'Créer un compte',
    'auth.link.toRegister': "Pas encore de compte ? S'inscrire",
    'auth.link.toLogin': 'Déjà inscrit ? Connectez-vous',
    'auth.error.required': 'Tous les champs sont requis',

    // Dashboard
    'dash.title': 'Tableau de Bord',
    'dash.subtitle': 'Synthèse de vos dépenses et analyses comparatives.',
    'dash.kpi.today': "Aujourd'hui",
    'dash.kpi.week': 'Cette Semaine',
    'dash.kpi.month': 'Ce Mois-ci',
    'dash.kpi.year': 'Cette Année',
    'dash.kpi.cumulative': 'Total Cumulé',
    'dash.savings.title': "Indice d'Économie",
    'dash.savings.desc': "Indice d'économie basé sur les meilleurs prix constatés",
    'dash.btn.newInvoice': 'Nouvelle facture',
    'dash.btn.refresh': 'Actualiser',
    'dash.recent.invoices': 'Dernières Factures',
    'dash.recent.purchases': 'Derniers Achats',
    'dash.view.all': 'Voir tout',
    'dash.no.invoices': 'Pas encore de facture enregistrée.',

    // KPIs & Analytics
    'kpi.title': 'KPIs & Analyses de Dépenses',
    'kpi.subtitle': 'Analyses détaillées de vos habitudes de consommation et variations tarifaires.',
    'kpi.tab.spending': 'Statistiques Dépenses',
    'kpi.tab.stores': 'Analyse des Enseignes',
    'kpi.tab.invoices': 'Analyse des Factures',
    'kpi.tab.products': 'Articles & Tarifs',
    'kpi.tab.productDetail': 'Suivi par Article',
    'kpi.spend.evolution': 'Évolution des dépenses',
    'kpi.spend.categories': 'Postes de dépenses',
    'kpi.store.history': 'Historique par Enseigne',
    'kpi.store.col.store': 'Magasin',
    'kpi.store.col.avg': 'Ticket Moyen',
    'kpi.store.col.visits': 'Visites',
    'kpi.store.col.total': 'Total Dépensé',
    'kpi.store.most_expensive': 'Enseigne la plus chère',
    'kpi.store.cheapest': 'Enseigne la plus économique',
    'kpi.invoice.stats': 'Statistiques de Factures',
    'kpi.invoice.total': 'Total Factures',
    'kpi.invoice.average': 'Montant Moyen',
    'kpi.invoice.max': 'Montant Maximum',
    'kpi.invoice.min': 'Montant Minimum',
    'kpi.product.stats': 'Statistiques Articles (Top 10)',
    'kpi.product.col.name': 'Article',
    'kpi.product.col.avg': 'Prix Moyen',
    'kpi.product.col.last': 'Dernier Prix',
    'kpi.product.col.min': 'Prix Min',
    'kpi.product.col.max': 'Prix Max',
    'kpi.inflation.title': 'Inflation & Variation de Prix',
    'kpi.inflation.desc': "Taux d'évolution moyen des prix observés sur les articles achetés plusieurs fois.",
    'kpi.inflation.rises': 'Plus fortes hausses',
    'kpi.inflation.drops': 'Plus fortes baisses',
    'kpi.productDetail.title': 'Suivi de Consommation par Article',
    'kpi.productDetail.search': 'Rechercher un article (ex: Lait 2L)...',
    'kpi.productDetail.card.qty': 'Quantité Totale Achetée',
    'kpi.productDetail.card.avg': 'Prix Unitaire Moyen',
    'kpi.productDetail.card.count': "Nombre d'achats analysés",
    'kpi.productDetail.chart.title': 'Volume et Prix unitaire',
    'kpi.productDetail.placeholder': "Saisissez ou sélectionnez un article ci-dessus pour afficher son historique de consommation.",
    'kpi.productDetail.no_data': "Aucun historique d'achat trouvé pour cet article.",

    // Invoices
    'inv.title': 'Gestion des Factures',
    'inv.subtitle': 'Consultez vos reçus ou numérisez vos photos de tickets de caisse via OCR.',
    'inv.filter.title': 'Filtrer les factures',
    'inv.filter.search': 'Rechercher une facture...',
    'inv.filter.store': 'Tous les magasins',
    'inv.filter.minPrice': 'Prix min',
    'inv.filter.maxPrice': 'Prix max',
    'inv.filter.reset': 'Réinitialiser',
    'inv.btn.add': 'Ajouter une facture',
    'inv.btn.delete_selected': 'Supprimer sélection',
    'inv.table.date': "Date d'achat",
    'inv.table.number': 'N° Facture',
    'inv.table.store': 'Magasin',
    'inv.table.total': 'Montant Total',
    'inv.table.pay': 'Paiement',
    'inv.table.actions': 'Actions',
    'inv.table.no_invoices': 'Aucune facture ne correspond aux filtres.',
    'inv.ocr.title': 'Numériser un Reçu par photo (OCR)',
    'inv.ocr.desc': 'Téléversez une photo de votre reçu. Le scanner de reçu FinTrack va automatiquement pré-remplir les articles, les prix unitaires, les taxes et les rabais.',
    'inv.ocr.btn.select': 'Sélectionner une photo de reçu',
    'inv.ocr.status.processing': 'Analyse OCR en cours...',
    'inv.ocr.status.loading': 'Chargement...',
    'inv.form.add': 'Enregistrer une nouvelle facture',
    'inv.form.edit': 'Modifier la facture',
    'inv.form.label.number': 'Numéro de facture *',
    'inv.form.label.date': "Date d'achat *",
    'inv.form.label.store': 'Magasin *',
    'inv.form.label.pay': 'Mode de paiement *',
    'inv.form.label.comment': 'Commentaires',
    'inv.form.label.file': 'Pièce jointe (Image)',
    'inv.form.items': 'Articles achetés',
    'inv.form.col.name': "Nom de l'article *",
    'inv.form.col.cat': 'Catégorie *',
    'inv.form.col.qty': 'Quantité *',
    'inv.form.col.unit': 'Unité',
    'inv.form.col.price': 'Prix unitaire *',
    'inv.form.col.totalht': 'Total (HT)',
    'inv.form.col.tax': 'Taxe %',
    'inv.form.col.discount': 'Rabais',
    'inv.form.btn.addline': '+ Ajouter une ligne',
    'inv.form.summary.subtotal': 'Sous-total (HT)',
    'inv.form.summary.taxes': 'Taxes cumulées',
    'inv.form.summary.discounts': 'Rabais totaux',
    'inv.form.summary.net': 'Net à payer (TTC)',
    'inv.form.btn.cancel': 'Annuler',
    'inv.form.btn.save': 'Enregistrer la facture',
    'inv.form.btn.update': 'Enregistrer les modifications',
    'inv.form.select.store': 'Sélectionner un magasin',
    'inv.form.select.cat': 'Catégorie',
    'inv.form.btn.newStore': '+ Nouveau magasin',
    'tour.btn.next': 'Suivant',
    'tour.btn.prev': 'Précédent',
    'tour.btn.skip': 'Passer',
    'tour.btn.finish': 'Terminer',
    'tour.step.of': 'Étape {current} sur {total}',
    'tour.step1.title': 'Scanner OCR (Beta) ⚡',
    'tour.step1.content': 'Glissez-déposez ou cliquez ici pour téléverser votre reçu. Notre OCR intelligent en extraira automatiquement la date, le magasin, le mode de paiement et tous vos articles !',
    'tour.step2.title': 'Détails de l\'achat 📝',
    'tour.step2.content': 'Saisissez les informations générales de la facture (numéro, date, magasin, moyen de paiement). Si vous utilisez l\'OCR, ces champs seront pré-remplis.',
    'tour.step3.title': 'Articles Achetés 🛒',
    'tour.step3.content': 'Ajoutez vos articles un par un. Le nom du produit bénéficie de l\'autocomplétion intelligente et sélectionne automatiquement sa catégorie la plus récente !',
    'tour.step4.title': 'Remise & Commentaires 💬',
    'tour.step4.content': 'Renseignez un éventuel rabais global appliqué sur l\'ensemble du ticket de caisse, et ajoutez des notes ou commentaires si nécessaire.',
    'tour.step5.title': 'Sauvegarder la Facture 💾',
    'tour.step5.content': 'Cliquez ici pour finaliser la création. Vos KPIs, budgets et analyses seront instantanément mis à jour !',

    // Stores
    'store.title': 'Analyse par Magasin',
    'store.subtitle': 'Gérez vos enseignes d\'achats et suivez vos statistiques de dépenses par commerce.',
    'store.btn.add': 'Ajouter un magasin',
    'store.filter.search': 'Rechercher un magasin...',
    'store.no_match': 'Aucun magasin ne correspond à votre recherche.',
    'store.card.visits': 'visites',
    'store.card.spent': 'Dépensé au total',
    'store.card.avg': 'Ticket moyen',
    'store.card.top': 'Articles les plus achetés',
    'store.modal.add': 'Ajouter un nouveau magasin',
    'store.modal.edit': 'Modifier le magasin',
    'store.modal.label.name': 'Nom du magasin *',
    'store.modal.label.country': 'Pays *',
    'store.modal.label.province': 'Province / État *',
    'store.modal.label.city': 'Ville *',
    'store.modal.label.phone': 'Téléphone',
    'store.modal.label.web': 'Site Web',
    'store.modal.btn.cancel': 'Annuler',
    'store.modal.btn.save': 'Enregistrer',

    // Products
    'prod.title': 'Catalogue des Articles',
    'prod.subtitle': 'Gérez la liste de vos produits et associez-les à des catégories de dépenses.',
    'prod.btn.add': 'Ajouter un article',
    'prod.filter.search': 'Rechercher un article par son nom...',
    'prod.filter.cat': 'Toutes les catégories',
    'prod.table.name': "Nom de l'article",
    'prod.table.cat': 'Catégorie par défaut',
    'prod.table.actions': 'Actions',
    'prod.table.no_match': 'Aucun article trouvé dans votre catalogue.',
    'prod.modal.add': 'Créer un nouvel article',
    'prod.modal.edit': "Modifier l'article",
    'prod.modal.label.name': "Nom de l'article *",
    'prod.modal.label.cat': 'Catégorie *',
    'prod.modal.btn.cancel': 'Annuler',
    'prod.modal.btn.save': 'Enregistrer',

    // Price Comparison
    'comp.title': 'Comparateur & Historique des Prix',
    'comp.subtitle': "Analysez les écarts de prix entre magasins et suivez la courbe d'inflation par produit.",
    'comp.search.placeholder': "Entrez le nom d'un produit (ex: Lait 2L, Riz 5kg, Essence...)",
    'comp.btn.search': 'Comparer les prix',
    'comp.status.searching': 'Recherche en cours...',
    'comp.placeholder': "Saisissez le nom d'un produit ci-dessus pour comparer ses prix.",
    'comp.placeholder.tip': 'Astuce : Essayez "Lait 2L" ou "Riz 5kg".',
    'comp.no_data': 'Aucun produit correspondant trouvé dans votre historique de factures.',
    'comp.kpi.min': 'Prix Minimum',
    'comp.kpi.min.desc': 'Disponible chez',
    'comp.kpi.max': 'Prix Maximum',
    'comp.kpi.max.desc': 'Constaté en magasin',
    'comp.kpi.avg': 'Prix Moyen',
    'comp.kpi.avg.desc': "Moyenne de l'historique",
    'comp.kpi.spread': 'Écart (Spread)',
    'comp.kpi.spread.desc': "Différence Max - Min",
    'comp.table.title': 'Dernier Prix par Enseigne',
    'comp.table.col.store': 'Magasin',
    'comp.table.col.price': 'Prix',
    'comp.table.col.date': 'Dernier Achat',
    'comp.chart.title': 'Évolution Historique & Inflation',
    'comp.chart.no_data': 'Données historiques insuffisantes pour tracer le graphique.',

    // Consumption
    'cons.title': 'Analyse de Consommation & Alertes',
    'cons.subtitle': "Visualisez vos volumes d'achats mensuels et gérez vos alertes de hausses de prix.",
    'cons.alerts.title': "Centre d'Alertes",
    'cons.alerts.success': '✓ Tout est sous contrôle. Aucune anomalie ou dépassement de budget détecté pour cette période.',
    'cons.alerts.col.show': 'Afficher',
    'cons.alerts.col.pages': 'alertes par page',
    'cons.alerts.range': 'Affichage de {start} à {end} sur {total} alertes',
    'cons.chart.milk': 'Volume Consommé: Lait 2L',
    'cons.chart.fuel': 'Volume Consommé: Carburant',
    'cons.chart.rice': 'Volume Consommé: Riz',
    'cons.chart.no_data': 'Aucune donnée de consommation.',
    'cons.frequent.title': 'Articles les plus achetés',
    'cons.frequent.subtitle': 'Vos produits de consommation courante.',
    'cons.frequent.col.product': 'Article',
    'cons.frequent.col.qty': 'Quantité totale',
    'cons.frequent.col.purchases': 'Achats',
    'cons.frequent.col.last': 'Dernier achat',
    'cons.abandoned.title': 'Articles non achetés récemment',
    'cons.abandoned.subtitle': 'Articles fréquemment achetés mais absents des derniers paniers.',
    'cons.abandoned.col.days': 'Absence (jours)',

    // Budgets
    'bud.title': 'Enveloppes Budgétaires',
    'bud.subtitle': 'Définissez des limites de dépenses par catégorie et suivez leur respect.',
    'bud.tracker.title': 'Suivi des Budgets',
    'bud.tracker.no_budgets': 'Aucun budget défini pour cette période. Utilisez le formulaire ci-contre pour en ajouter.',
    'bud.tracker.used': 'utilisé',
    'bud.tracker.exceeded': 'Dépassement de',
    'bud.tracker.loading': 'Mise à jour...',
    'bud.edit_btn': 'Modifier le budget',
    'bud.delete_btn': 'Supprimer le budget',
    'bud.shopping.reason': 'Achat suggéré (Dernier achat il y a {days} jours. Habituellement acheté tous les 7 jours)',
    'bud.form.title.add': 'Définir une limite',
    'bud.form.title.edit': 'Modifier la limite',
    'bud.form.label.amount': 'Montant du budget',
    'bud.form.label.cat': 'Catégorie',
    'bud.form.cat.global': 'Budget Global (Toutes dépenses)',
    'bud.form.btn.cancel': 'Annuler',
    'bud.form.btn.save': 'Enregistrer le budget',
    'bud.form.btn.update': 'Mettre à jour',
    'bud.shopping.title': "Liste d'Achats Intelligente",
    'bud.shopping.desc': 'Le système suggère automatiquement des articles à votre liste selon vos fréquences et cycles d\'achat habituels.',
    'bud.shopping.success': 'Votre garde-manger semble complet ! Aucune suggestion automatique requise pour aujourd\'hui.',

    // Settings
    'set.title': 'Paramètres du Compte',
    'set.subtitle': 'Gérez vos informations de profil, vos préférences de devise et la sécurité de votre compte.',
    'set.tab.profile': 'Profil',
    'set.tab.security': 'Sécurité',
    'set.profile.title': 'Informations personnelles & Préférences',
    'set.profile.label.name': 'Nom complet',
    'set.profile.label.currency': 'Devise globale',
    'set.profile.label.pay': 'Mode de paiement par défaut',
    'set.profile.btn.save': 'Sauvegarder les modifications',
    'set.security.btn.save': 'Modifier le mot de passe',

    // Common / Global / Pagination / Other
    'common.confirm.delete': 'Voulez-vous supprimer cet élément ?',
    'common.error.loading': 'Chargement...',
    'common.error.occurred': 'Une erreur est survenue',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.update': 'Mettre à jour',
    'common.saving': 'Enregistrement...',
    'common.deleting': 'Suppression...',
    'common.loading': 'Chargement...',
    
    // Pagination
    'pag.show': 'Afficher',
    'pag.lines_per_page': 'lignes par page',
    'pag.display_products': 'Affichage de {start} à {end} sur {total} articles',
    'pag.display_stores': 'Affichage de {start} à {end} sur {total} magasins',
    'pag.display_invoices': 'Affichage de {start} à {end} sur {total} factures',
    'pag.display_alerts': 'Affichage de {start} à {end} sur {total} alertes',
    'pag.prev': 'Précédent',
    'pag.next': 'Suivant',
    'pag.page_of': 'Page {current} sur {total}',

    // Budgets additions
    'bud.delete.confirm': 'Voulez-vous supprimer ce budget ?',
    'bud.error.save': 'Erreur lors de l\'enregistrement du budget',
    'bud.error.delete': 'Erreur lors de la suppression du budget',

    // Settings additions
    'set.tab.profile.title': 'Profil & Préférences',
    'set.tab.security.title': 'Sécurité & Accès',
    'set.profile.section.title': 'Informations personnelles & Devise',
    'set.profile.label.email': 'Adresse e-mail',
    'set.profile.success': 'Profil mis à jour avec succès !',
    'set.profile.error': 'Erreur lors de la mise à jour.',
    'set.security.mismatch': 'Les nouveaux mots de passe ne correspondent pas.',
    'set.security.success': 'Mot de passe modifié avec succès !',
    'set.security.error': 'Erreur lors de la mise à jour du mot de passe.',
    'set.btn.saving': 'Enregistrement...',
    'set.btn.modifying': 'Modification...',
    'set.pay.debit_card': 'Carte Débit',
    'set.pay.credit_card': 'Carte Crédit',
    'set.pay.cash': 'Espèces',
    'set.pay.wire_transfer': 'Virement',
    'set.pay.other': 'Autre',

    // Products additions
    'prod.delete.confirm': 'Voulez-vous vraiment supprimer cet article de votre catalogue ?',
    'prod.error.delete': 'Erreur lors de la suppression de l\'article',
    'prod.error.name_required': 'Le nom de l\'article est requis',
    'prod.error.cat_required': 'Veuillez sélectionner une catégorie',
    'prod.error.save': 'Une erreur est survenue lors de l\'enregistrement',
    'prod.loading': 'Chargement du catalogue d\'articles...',
    'prod.empty.title': 'Votre catalogue est vide',
    'prod.empty.desc': 'Commencez à ajouter des articles pour pouvoir les affecter rapidement lors de vos analyses.',
    'prod.empty.btn': 'Créer mon premier article',
    'prod.filter.empty': 'Aucun article trouvé',
    'prod.filter.empty_desc': 'Essayez de modifier vos critères de recherche ou de filtre.',
    'prod.table.cat_none': 'Sans catégorie',
    'prod.modal.select_cat': 'Sélectionner une catégorie',
    'prod.modal.btn.create': 'Créer l\'article',
    'prod.modal.btn.update': 'Enregistrer les modifications',
    'prod.modal.saving': 'Enregistrement...',

    // Stores additions
    'store.error.load': 'Erreur lors du chargement des détails du magasin',
    'store.delete.confirm': 'Voulez-vous vraiment supprimer ce magasin ? Cette action supprimera également toutes les factures associées.',
    'store.error.delete': 'Erreur lors de la suppression du magasin',
    'store.error.save': 'Erreur lors de l\'enregistrement du magasin',
    'store.loading': 'Chargement des données magasins...',
    'store.filter.search_placeholder': 'Rechercher un magasin par son nom...',
    'store.empty': 'Aucun magasin enregistré.',
    'store.empty_search': 'Aucun magasin ne correspond à "{query}".',
    'store.card.spent_title': 'Dépenses Totales',
    'store.card.invoice_count': 'Nombre de factures :',
    'store.card.quantity': 'qté:',
    'store.modal.type': 'Type de commerce',
    'store.modal.address': 'Adresse postale (facultatif)',
    'store.modal.phone_opt': 'Téléphone (facultatif)',
    'store.modal.web_opt': 'Site Web (facultatif)',
    'store.modal.btn.create': 'Créer le magasin',
    'store.modal.btn.update': 'Enregistrer les modifications',
    'store.modal.saving': 'Enregistrement...',
    'store.type.supermarket': 'Supermarché / Alimentation',
    'store.type.pharmacy': 'Pharmacie',
    'store.type.gas_station': 'Station-service / Essence',
    'store.type.transport': 'Transport',
    'store.type.retail': 'Vente au détail',
    'store.type.restau': 'Restaurant / Café',
    'store.type.other': 'Autre',

    // Price Comparison additions
    'comp.kpi.spread.footer': 'Différence Max - Min ({percent}% d\'écart)',

    // Consumption additions
    'cons.loading': 'Chargement des analyses de consommation...',
    'cons.chart.no_data_simple': 'Aucune donnée.',
    'cons.frequent.title_simple': 'Produits achetés fréquemment',
    'cons.frequent.purchased_count': '{count} {unit} achetés',
    'cons.abandoned.title_simple': 'Produits abandonnés (>3 mois)',
    'cons.abandoned.empty': 'Aucun produit abandonné.',
    'cons.abandoned.last_date': 'Dernier : {date}',

    // Invoices additions
    'inv.confirm.delete_selected': 'Voulez-vous vraiment supprimer les factures sélectionnées ?',
    'inv.confirm.delete_one': 'Voulez-vous vraiment supprimer cette facture ?',
    'inv.error.delete': 'Erreur lors de la suppression',
    'inv.error.load': 'Erreur lors du chargement de la facture',
    'inv.ocr.error.no_file': 'Veuillez d\'abord sélectionner une image de reçu.',
    'inv.ocr.error.process': 'Échec de l\'analyse OCR.',
    'inv.ocr.status.ready': 'Glissez-déposez ou cliquez pour téléverser votre reçu (JPEG, PNG)',
    'inv.ocr.status.analyzed': 'Analyse réussie ! Les informations ont été pré-remplies ci-dessous.',
    'inv.form.error.no_items': 'Veuillez ajouter au moins un article',
    'inv.form.error.save': 'Erreur lors de l\'enregistrement',
    'inv.form.btn.updating': 'Enregistrement...',
    'inv.form.btn.saving': 'Enregistrement...',
    'inv.form.col.total': 'Total (HT)',
    'inv.form.select.store_placeholder': 'Sélectionner ou saisir un magasin...',
    'inv.form.select.pay_placeholder': 'Mode de paiement',
    'inv.form.select.cat_placeholder': 'Catégorie...',
    'inv.form.select.unit_placeholder': 'Unité...',
    'inv.details.title': 'Détails de la Facture',
    'inv.details.btn.back': 'Retour',
    'inv.details.number': 'Numéro de facture',
    'inv.details.date': 'Date d\'achat',
    'inv.details.store': 'Magasin d\'achat',
    'inv.details.payment': 'Mode de paiement',
    'inv.details.comment': 'Commentaires',
    'inv.details.image': 'Image du reçu',
    'inv.details.image.none': 'Aucune image de reçu disponible',
    'inv.details.items': 'Articles achetés',
    'inv.details.subtotal': 'Sous-total (HT)',
    'inv.details.taxes': 'Taxes cumulées',
    'inv.details.discounts': 'Rabais totaux',
    'inv.details.net': 'Net payé (TTC)',
    'inv.details.btn.edit': 'Modifier la facture',
    'inv.details.btn.delete': 'Supprimer la facture',
    'inv.form.btn.add': 'Enregistrer',
    'inv.form.autocomplete.product': 'Entrez le nom du produit...',
    'inv.form.autocomplete.store': 'Rechercher ou ajouter un magasin...',
    'inv.ocr.beta': 'Note : cette fonctionnalité est encore en version beta.',

    // KPIs additions
    'kpi.loading': 'Calcul et agrégation des indicateurs clés...',
    'kpi.error.load': 'Impossible de charger les indicateurs de performance. Veuillez réessayer plus tard.',
    'kpi.tab.evolution': 'Évolution & Tendances',
    'kpi.tab.categories': 'Postes de Dépense',
    'kpi.tab.inflation': 'Inflation Personnelle',
    'kpi.tab.taxes': 'TVA & Taxes',
    'kpi.spend.evolution.monthly': 'Variation Mensuelle',
    'kpi.spend.this_month': 'Dépenses ce mois-ci',
    'kpi.spend.prev_month': 'Mois précédent',
    'kpi.spend.monthly_trend': 'Tendance mensuelle',
    'kpi.spend.trend.up': 'En hausse de {percent}% par rapport au mois dernier',
    'kpi.spend.trend.down': 'En baisse de {percent}% par rapport au mois dernier',
    'kpi.spend.trend.stable': 'Stable par rapport au mois dernier',
    'kpi.spend.three_month': 'Moyenne sur 3 mois',
    'kpi.spend.twelve_month': 'Moyenne sur 12 mois',
    'kpi.spend.max_month': 'Mois le plus dépensier',
    'kpi.categories.budget_share': 'Part du budget global',
    'kpi.categories.most_costly': 'Catégorie la plus coûteuse',
    'kpi.categories.no_budget': 'Pas de budget',
    'kpi.store.frequent': 'Magasin le plus fréquenté',
    'kpi.store.frequent.desc': 'avec {count} visites',
    'kpi.invoice.count': 'Nombre total de factures',
    'kpi.invoice.monthly_dist': 'Répartition mensuelle des factures',
    'kpi.inflation.evolution': 'Taux d\'évolution moyen des prix observés',
    'kpi.inflation.empty': 'Données d\'achats insuffisantes pour calculer l\'inflation.',
    'kpi.inflation.rise_pct': '+{percent}%',
    'kpi.inflation.drop_pct': '{percent}%',
    'kpi.taxes.total': 'TVA totale cumulée',
    'kpi.taxes.share': 'Part des taxes dans vos dépenses',
    'kpi.taxes.by_category': 'Part de TVA payée par catégorie',
    'kpi.taxes.by_store': 'Répartition de la TVA par magasin',
    'kpi.taxes.total_tva': 'Total TVA',
    'kpi.taxes.col.category': 'Catégorie',
    'kpi.taxes.col.tax': 'TVA Payée',
    'kpi.taxes.col.share': 'Part',
    'kpi.taxes.col.store': 'Magasin',
    'kpi.productDetail.qty_purchased': 'Quantité Totale Achetée',
    'kpi.productDetail.avg_price': 'Prix Unitaire Moyen',
    'kpi.productDetail.purchases_count': 'Nombre d\'achats analysés',
    'kpi.productDetail.qty_axis': 'Volume (Quantité)',
    'kpi.productDetail.price_axis': 'Prix Unitaire',
    'kpi.productDetail.qty_series': 'Volume consommé',
    'kpi.productDetail.price_series': 'Prix unitaire payé',
    'kpi.productDetail.recent_purchases': '20 derniers achats de {product}',
    'kpi.productDetail.table.date': 'Date',
    'kpi.productDetail.table.store': 'Magasin',
    'kpi.productDetail.table.qty': 'Quantité',
    'kpi.productDetail.table.price': 'Prix U.',
    'kpi.productDetail.table.total': 'Total',
  },
  en: {
    // Sidebar / Navigation
    'nav.dashboard': 'Dashboard',
    'nav.kpis': 'KPIs & Analytics',
    'nav.invoices': 'Invoices & OCR',
    'nav.stores': 'Stores',
    'nav.articles': 'Products',
    'nav.prices': 'Price Comparator',
    'nav.consumption': 'Consumption & Alerts',
    'nav.budgets': 'Budgets',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'role.admin': 'Administrator',
    'role.family': 'Family Member',
    'role.user': 'Simple User',
    'app.init': 'Initializing FinTrack...',
    'dash.welcome': 'Hello',
    'dash.welcome.desc': 'Here is the current status of your spending and financial analysis.',
    'dash.overview': 'Spending Overview',
    'dash.kpi.today.footer': "Today's expenses",
    'dash.kpi.week.footer': "This week's expenses",
    'dash.kpi.month.footer': 'monthly invoices',
    'dash.kpi.year.footer': 'Annual total',
    'dash.kpi.cumulative.footer': 'Historical total',
    'dash.items.title': 'Purchased Items',
    'dash.items.footer': 'total invoices in FinTrack',
    'dash.savings.footer': 'Cumulative potential savings this year by buying at the minimum observed price!',
    'dash.category.breakdown': 'Breakdown by Category',
    'dash.store.breakdown': 'Expenses by Store',
    'dash.recent.no_purchases': 'No recent purchases.',
    'dash.recent.no_invoices': 'No recent invoices.',
    'dash.loading': 'Loading dashboard...',
    'dash.total': 'Total',
    'dash.no_data': 'No data to display.',

    // Auth / Login
    'auth.title.login': 'Sign in to FinTrack',
    'auth.title.register': 'Create a FinTrack account',
    'auth.subtitle.login': 'Sign in to manage your expenses',
    'auth.subtitle.register': 'Create a family or user account',
    'auth.label.name': 'Full Name *',
    'auth.label.email': 'Email *',
    'auth.label.password': 'Password *',
    'auth.btn.login': 'Sign In',
    'auth.btn.register': 'Create Account',
    'auth.link.toRegister': "Don't have an account? Sign up",
    'auth.link.toLogin': 'Already registered? Log in',
    'auth.error.required': 'All fields are required',

    // Dashboard
    'dash.title': 'Dashboard',
    'dash.subtitle': 'Summary of your expenses and comparative analyses.',
    'dash.kpi.today': 'Today',
    'dash.kpi.week': 'This Week',
    'dash.kpi.month': 'This Month',
    'dash.kpi.year': 'This Year',
    'dash.kpi.cumulative': 'Cumulative Total',
    'dash.savings.title': 'Savings Index',
    'dash.savings.desc': 'Savings index based on best observed prices',
    'dash.btn.newInvoice': 'New Invoice',
    'dash.btn.refresh': 'Refresh',
    'dash.recent.invoices': 'Latest Invoices',
    'dash.recent.purchases': 'Latest Purchases',
    'dash.view.all': 'View All',
    'dash.no.invoices': 'No invoices registered yet.',

    // KPIs & Analytics
    'kpi.title': 'KPIs & Spending Analysis',
    'kpi.subtitle': 'Detailed analysis of your consumption habits and price variations.',
    'kpi.tab.spending': 'Spending Stats',
    'kpi.tab.stores': 'Store Analysis',
    'kpi.tab.invoices': 'Invoice Analysis',
    'kpi.tab.products': 'Products & Prices',
    'kpi.tab.productDetail': 'Product Tracking',
    'kpi.spend.evolution': 'Spending evolution',
    'kpi.spend.categories': 'Spending categories',
    'kpi.store.history': 'Store History',
    'kpi.store.col.store': 'Store',
    'kpi.store.col.avg': 'Average Ticket',
    'kpi.store.col.visits': 'Visits',
    'kpi.store.col.total': 'Total Spent',
    'kpi.store.most_expensive': 'Most expensive store',
    'kpi.store.cheapest': 'Most economical store',
    'kpi.invoice.stats': 'Invoice Statistics',
    'kpi.invoice.total': 'Total Invoices',
    'kpi.invoice.average': 'Average Amount',
    'kpi.invoice.max': 'Maximum Amount',
    'kpi.invoice.min': 'Minimum Amount',
    'kpi.product.stats': 'Product Statistics (Top 10)',
    'kpi.product.col.name': 'Product',
    'kpi.product.col.avg': 'Average Price',
    'kpi.product.col.last': 'Last Price',
    'kpi.product.col.min': 'Min Price',
    'kpi.product.col.max': 'Max Price',
    'kpi.inflation.title': 'Inflation & Price Variation',
    'kpi.inflation.desc': 'Average price evolution rate for items bought multiple times.',
    'kpi.inflation.rises': 'Top price hikes',
    'kpi.inflation.drops': 'Top price drops',
    'kpi.productDetail.title': 'Product Consumption History',
    'kpi.productDetail.search': 'Search for an item (e.g. Milk 2L)...',
    'kpi.productDetail.card.qty': 'Total Quantity Purchased',
    'kpi.productDetail.card.avg': 'Average Unit Price',
    'kpi.productDetail.card.count': 'Number of purchases analyzed',
    'kpi.productDetail.chart.title': 'Volume and Unit Price',
    'kpi.productDetail.placeholder': 'Enter or select a product above to display its consumption history.',
    'kpi.productDetail.no_data': 'No purchase history found for this product.',

    // Invoices
    'inv.title': 'Manage Invoices',
    'inv.subtitle': 'Consult your receipts or scan your receipt photos via OCR.',
    'inv.filter.title': 'Filter Invoices',
    'inv.filter.search': 'Search for an invoice...',
    'inv.filter.store': 'All stores',
    'inv.filter.minPrice': 'Min price',
    'inv.filter.maxPrice': 'Max price',
    'inv.filter.reset': 'Reset',
    'inv.btn.add': 'Add an Invoice',
    'inv.btn.delete_selected': 'Delete Selected',
    'inv.table.date': 'Purchase Date',
    'inv.table.number': 'Invoice N°',
    'inv.table.store': 'Store',
    'inv.table.total': 'Total Amount',
    'inv.table.pay': 'Payment',
    'inv.table.actions': 'Actions',
    'inv.table.no_invoices': 'No invoices match the filters.',
    'inv.ocr.title': 'Scan a Receipt by Photo (OCR)',
    'inv.ocr.desc': 'Upload a photo of your receipt. FinTrack scanner will automatically extract products, unit prices, quantities, taxes, and discounts.',
    'inv.ocr.btn.select': 'Select a receipt photo',
    'inv.ocr.status.processing': 'OCR analysis in progress...',
    'inv.ocr.status.loading': 'Loading...',
    'inv.form.add': 'Record a New Invoice',
    'inv.form.edit': 'Edit Invoice',
    'inv.form.label.number': 'Invoice number *',
    'inv.form.label.date': 'Purchase date *',
    'inv.form.label.store': 'Store *',
    'inv.form.label.pay': 'Payment mode *',
    'inv.form.label.comment': 'Comments',
    'inv.form.label.file': 'Attachment (Image)',
    'inv.form.items': 'Purchased items',
    'inv.form.col.name': 'Product name *',
    'inv.form.col.cat': 'Category *',
    'inv.form.col.qty': 'Quantity *',
    'inv.form.col.unit': 'Unit',
    'inv.form.col.price': 'Unit price *',
    'inv.form.col.totalht': 'Subtotal',
    'inv.form.col.tax': 'Tax %',
    'inv.form.col.discount': 'Discount',
    'inv.form.btn.addline': '+ Add a line',
    'inv.form.summary.subtotal': 'Subtotal (Net)',
    'inv.form.summary.taxes': 'Cumulative taxes',
    'inv.form.summary.discounts': 'Total discounts',
    'inv.form.summary.net': 'Net to pay (TTC)',
    'inv.form.btn.cancel': 'Cancel',
    'inv.form.btn.save': 'Save Invoice',
    'inv.form.btn.update': 'Save Changes',
    'inv.form.select.store': 'Select a store',
    'inv.form.select.cat': 'Category',
    'inv.form.btn.newStore': '+ New store',
    'tour.btn.next': 'Next',
    'tour.btn.prev': 'Previous',
    'tour.btn.skip': 'Skip',
    'tour.btn.finish': 'Finish',
    'tour.step.of': 'Step {current} of {total}',
    'tour.step1.title': 'OCR Scanner (Beta) ⚡',
    'tour.step1.content': 'Drag and drop or click here to upload your receipt. Our smart OCR will automatically extract the date, store, payment mode, and all your items!',
    'tour.step2.title': 'Purchase Details 📝',
    'tour.step2.content': 'Enter the general information of the invoice (number, date, store, payment method). If you use OCR, these fields will be pre-filled.',
    'tour.step3.title': 'Purchased Items 🛒',
    'tour.step3.content': 'Add your items one by one. The product name features smart autocomplete and automatically selects its most recent category!',
    'tour.step4.title': 'Discount & Comments 💬',
    'tour.step4.content': 'Fill in any global discount applied to the entire receipt, and add custom notes or comments if needed.',
    'tour.step5.title': 'Save the Invoice 💾',
    'tour.step5.content': 'Click here to finalize the creation. Your KPIs, budgets, and analytics will be updated instantly!',

    // Stores
    'store.title': 'Store Analysis',
    'store.subtitle': 'Manage your shopping stores and track your spending statistics by brand.',
    'store.btn.add': 'Add a Store',
    'store.filter.search': 'Search for a store...',
    'store.no_match': 'No stores match your search.',
    'store.card.visits': 'visits',
    'store.card.spent': 'Total spent',
    'store.card.avg': 'Average ticket',
    'store.card.top': 'Top purchased items',
    'store.modal.add': 'Add a New Store',
    'store.modal.edit': 'Edit Store',
    'store.modal.label.name': 'Store Name *',
    'store.modal.label.country': 'Country *',
    'store.modal.label.province': 'Province / State *',
    'store.modal.label.city': 'City *',
    'store.modal.label.phone': 'Phone',
    'store.modal.label.web': 'Website',
    'store.modal.btn.cancel': 'Cancel',
    'store.modal.btn.save': 'Save',

    // Products
    'prod.title': 'Product Catalog',
    'prod.subtitle': 'Manage your product list and associate them with budget categories.',
    'prod.btn.add': 'Add a Product',
    'prod.filter.search': 'Search for a product by name...',
    'prod.filter.cat': 'All categories',
    'prod.table.name': 'Product Name',
    'prod.table.cat': 'Default Category',
    'prod.table.actions': 'Actions',
    'prod.table.no_match': 'No products found in your catalog.',
    'prod.modal.add': 'Create New Product',
    'prod.modal.edit': 'Edit Product',
    'prod.modal.label.name': 'Product Name *',
    'prod.modal.label.cat': 'Category *',
    'prod.modal.btn.cancel': 'Cancel',
    'prod.modal.btn.save': 'Save',

    // Price Comparison
    'comp.title': 'Price Comparison & History',
    'comp.subtitle': 'Analyze price spreads across stores and track the inflation curve per product.',
    'comp.search.placeholder': 'Enter the name of a product (e.g. Milk 2L, Rice 5kg, Fuel...)',
    'comp.btn.search': 'Compare Prices',
    'comp.status.searching': 'Searching...',
    'comp.placeholder': 'Enter a product name above to compare its prices.',
    'comp.placeholder.tip': 'Tip: Try "Milk 2L" or "Rice 5kg".',
    'comp.no_data': 'No matching product found in your invoice history.',
    'comp.kpi.min': 'Minimum Price',
    'comp.kpi.min.desc': 'Available at',
    'comp.kpi.max': 'Maximum Price',
    'comp.kpi.max.desc': 'Observed in store',
    'comp.kpi.avg': 'Average Price',
    'comp.kpi.avg.desc': 'History average',
    'comp.kpi.spread': 'Price Spread',
    'comp.kpi.spread.desc': 'Max - Min Difference',
    'comp.table.title': 'Latest Price per Brand',
    'comp.table.col.store': 'Store',
    'comp.table.col.price': 'Price',
    'comp.table.col.date': 'Last Purchase',
    'comp.chart.title': 'Historical Evolution & Inflation',
    'comp.chart.no_data': 'Insufficient historical data to plot the chart.',

    // Consumption
    'cons.title': 'Consumption & Alerts Analysis',
    'cons.subtitle': 'Visualize your monthly purchase volumes and manage price increase alerts.',
    'cons.alerts.title': 'Alerts Center',
    'cons.alerts.success': '✓ Everything is under control. No anomalies or budget overruns detected for this period.',
    'cons.alerts.col.show': 'Show',
    'cons.alerts.col.pages': 'alerts per page',
    'cons.alerts.range': 'Showing {start} to {end} of {total} alerts',
    'cons.chart.milk': 'Volume Consumed: Milk 2L',
    'cons.chart.fuel': 'Volume Consommed: Fuel',
    'cons.chart.rice': 'Volume Consommed: Rice',
    'cons.chart.no_data': 'No consumption data.',
    'cons.frequent.title': 'Top Purchased Items',
    'cons.frequent.subtitle': 'Your everyday consumption items.',
    'cons.frequent.col.product': 'Product',
    'cons.frequent.col.qty': 'Total quantity',
    'cons.frequent.col.purchases': 'Purchases',
    'cons.frequent.col.last': 'Last purchase',
    'cons.abandoned.title': 'Items not purchased recently',
    'cons.abandoned.subtitle': 'Items frequently bought but absent from recent baskets.',
    'cons.abandoned.col.days': 'Absence (days)',

    // Budgets
    'bud.title': 'Budget Envelopes',
    'bud.subtitle': 'Define spending limits by category and track their compliance.',
    'bud.tracker.title': 'Budget Tracking',
    'bud.tracker.no_budgets': 'No budgets defined for this period. Use the form to add one.',
    'bud.tracker.used': 'used',
    'bud.tracker.exceeded': 'Overrun of',
    'bud.tracker.loading': 'Updating...',
    'bud.edit_btn': 'Edit budget',
    'bud.delete_btn': 'Delete budget',
    'bud.shopping.reason': 'Suggested purchase (Last purchase was {days} days ago. Usually bought every 7 days)',
    'bud.form.title.add': 'Define a limit',
    'bud.form.title.edit': 'Edit Limit',
    'bud.form.label.amount': 'Budget Amount',
    'bud.form.label.cat': 'Category',
    'bud.form.cat.global': 'Global Budget (All expenses)',
    'bud.form.btn.cancel': 'Cancel',
    'bud.form.btn.save': 'Save Budget',
    'bud.form.btn.update': 'Update',
    'bud.shopping.title': 'Smart Shopping List',
    'bud.shopping.desc': 'The system automatically suggests items to your list based on your usual shopping cycles and frequencies.',
    'bud.shopping.success': 'Your pantry seems full! No automatic suggestions needed today.',

    // Settings
    'set.title': 'Account Settings',
    'set.subtitle': 'Manage your profile information, currency preferences, and account security.',
    'set.tab.profile': 'Profile',
    'set.tab.security': 'Security',
    'set.profile.title': 'Personal Info & Preferences',
    'set.profile.label.name': 'Full Name',
    'set.profile.label.currency': 'Global Currency',
    'set.profile.label.pay': 'Default Payment Mode',
    'set.profile.btn.save': 'Save Changes',
    'set.security.btn.save': 'Change Password',

    // Common / Global / Pagination / Other
    'common.confirm.delete': 'Are you sure you want to delete this item?',
    'common.error.loading': 'Loading...',
    'common.error.occurred': 'An error occurred',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.update': 'Update',
    'common.saving': 'Saving...',
    'common.deleting': 'Deleting...',
    'common.loading': 'Loading...',
    
    // Pagination
    'pag.show': 'Show',
    'pag.lines_per_page': 'lines per page',
    'pag.display_products': 'Showing {start} to {end} of {total} products',
    'pag.display_stores': 'Showing {start} to {end} of {total} stores',
    'pag.display_invoices': 'Showing {start} to {end} of {total} invoices',
    'pag.display_alerts': 'Showing {start} to {end} of {total} alerts',
    'pag.prev': 'Previous',
    'pag.next': 'Next',
    'pag.page_of': 'Page {current} of {total}',

    // Budgets additions
    'bud.delete.confirm': 'Do you want to delete this budget?',
    'bud.error.save': 'Error saving budget',
    'bud.error.delete': 'Error deleting budget',

    // Settings additions
    'set.tab.profile.title': 'Profile & Preferences',
    'set.tab.security.title': 'Security & Access',
    'set.profile.section.title': 'Personal Info & Currency',
    'set.profile.label.email': 'Email Address',
    'set.profile.success': 'Profile updated successfully!',
    'set.profile.error': 'Error updating profile.',
    'set.security.mismatch': 'New passwords do not match.',
    'set.security.success': 'Password changed successfully!',
    'set.security.error': 'Error changing password.',
    'set.btn.saving': 'Saving...',
    'set.btn.modifying': 'Modifying...',
    'set.pay.debit_card': 'Debit Card',
    'set.pay.credit_card': 'Credit Card',
    'set.pay.cash': 'Cash',
    'set.pay.wire_transfer': 'Bank Transfer',
    'set.pay.other': 'Other',

    // Products additions
    'prod.delete.confirm': 'Are you sure you want to delete this product from your catalog?',
    'prod.error.delete': 'Error deleting product',
    'prod.error.name_required': 'Product name is required',
    'prod.error.cat_required': 'Please select a category',
    'prod.error.save': 'An error occurred while saving',
    'prod.loading': 'Loading product catalog...',
    'prod.empty.title': 'Your catalog is empty',
    'prod.empty.desc': 'Start adding products to assign them quickly during your analyses.',
    'prod.empty.btn': 'Create my first product',
    'prod.filter.empty': 'No products found',
    'prod.filter.empty_desc': 'Try changing your search or filter criteria.',
    'prod.table.cat_none': 'No category',
    'prod.modal.select_cat': 'Select a category',
    'prod.modal.btn.create': 'Create Product',
    'prod.modal.btn.update': 'Save Changes',
    'prod.modal.saving': 'Saving...',

    // Stores additions
    'store.error.load': 'Error loading store details',
    'store.delete.confirm': 'Are you sure you want to delete this store? This action will also delete all associated invoices.',
    'store.error.delete': 'Error deleting store',
    'store.error.save': 'Error saving store',
    'store.loading': 'Loading store data...',
    'store.filter.search_placeholder': 'Search store by name...',
    'store.empty': 'No stores registered.',
    'store.empty_search': 'No stores match "{query}".',
    'store.card.spent_title': 'Total Spent',
    'store.card.invoice_count': 'Number of invoices:',
    'store.card.quantity': 'qty:',
    'store.modal.type': 'Business Type',
    'store.modal.address': 'Postal Address (optional)',
    'store.modal.phone_opt': 'Phone (optional)',
    'store.modal.web_opt': 'Website (optional)',
    'store.modal.btn.create': 'Create Store',
    'store.modal.btn.update': 'Save Changes',
    'store.modal.saving': 'Saving...',
    'store.type.supermarket': 'Supermarket / Grocery',
    'store.type.pharmacy': 'Pharmacy',
    'store.type.gas_station': 'Gas Station',
    'store.type.transport': 'Transport',
    'store.type.retail': 'Retail',
    'store.type.restau': 'Restaurant / Cafe',
    'store.type.other': 'Other',

    // Price Comparison additions
    'comp.kpi.spread.footer': 'Max - Min Difference ({percent}% spread)',

    // Consumption additions
    'cons.loading': 'Loading consumption analytics...',
    'cons.chart.no_data_simple': 'No data.',
    'cons.frequent.title_simple': 'Frequently purchased products',
    'cons.frequent.purchased_count': '{count} {unit} purchased',
    'cons.abandoned.title_simple': 'Abandoned products (>3 months)',
    'cons.abandoned.empty': 'No abandoned products.',
    'cons.abandoned.last_date': 'Last: {date}',

    // Invoices additions
    'inv.confirm.delete_selected': 'Are you sure you want to delete the selected invoices?',
    'inv.confirm.delete_one': 'Are you sure you want to delete this invoice?',
    'inv.error.delete': 'Error during deletion',
    'inv.error.load': 'Error loading invoice',
    'inv.ocr.error.no_file': 'Please select a receipt image first.',
    'inv.ocr.error.process': 'OCR analysis failed.',
    'inv.ocr.status.ready': 'Drag & drop or click to upload your receipt (JPEG, PNG)',
    'inv.ocr.status.analyzed': 'Analysis successful! Information has been pre-filled below.',
    'inv.form.error.no_items': 'Please add at least one item',
    'inv.form.error.save': 'Error during saving',
    'inv.form.btn.updating': 'Saving...',
    'inv.form.btn.saving': 'Saving...',
    'inv.form.col.total': 'Total',
    'inv.form.select.store_placeholder': 'Select or enter a store...',
    'inv.form.select.pay_placeholder': 'Payment Mode',
    'inv.form.select.cat_placeholder': 'Category...',
    'inv.form.select.unit_placeholder': 'Unit...',
    'inv.details.title': 'Invoice Details',
    'inv.details.btn.back': 'Back',
    'inv.details.number': 'Invoice number',
    'inv.details.date': 'Purchase date',
    'inv.details.store': 'Store',
    'inv.details.payment': 'Payment mode',
    'inv.details.comment': 'Comments',
    'inv.details.image': 'Receipt Image',
    'inv.details.image.none': 'No receipt image available',
    'inv.details.items': 'Purchased items',
    'inv.details.subtotal': 'Subtotal',
    'inv.details.taxes': 'Cumulative taxes',
    'inv.details.discounts': 'Total discounts',
    'inv.details.net': 'Net paid (TTC)',
    'inv.details.btn.edit': 'Edit Invoice',
    'inv.details.btn.delete': 'Delete Invoice',
    'inv.form.btn.add': 'Save',
    'inv.form.autocomplete.product': 'Enter product name...',
    'inv.form.autocomplete.store': 'Search or add a store...',
    'inv.ocr.beta': 'Note: this feature is still in beta.',

    // KPIs additions
    'kpi.loading': 'Calculating and aggregating key indicators...',
    'kpi.error.load': 'Could not load key performance indicators. Please try again later.',
    'kpi.tab.evolution': 'Evolution & Trends',
    'kpi.tab.categories': 'Spending Categories',
    'kpi.tab.inflation': 'Personal Inflation',
    'kpi.tab.taxes': 'VAT & Taxes',
    'kpi.spend.evolution.monthly': 'Monthly Variation',
    'kpi.spend.this_month': 'Expenses this month',
    'kpi.spend.prev_month': 'Previous month',
    'kpi.spend.monthly_trend': 'Monthly trend',
    'kpi.spend.trend.up': 'Up by {percent}% compared to last month',
    'kpi.spend.trend.down': 'Down by {percent}% compared to last month',
    'kpi.spend.trend.stable': 'Stable compared to last month',
    'kpi.spend.three_month': '3-month average',
    'kpi.spend.twelve_month': '12-month average',
    'kpi.spend.max_month': 'Most expensive month',
    'kpi.categories.budget_share': 'Share of global budget',
    'kpi.categories.most_costly': 'Most expensive category',
    'kpi.categories.no_budget': 'No budget',
    'kpi.store.frequent': 'Most frequent store',
    'kpi.store.frequent.desc': 'with {count} visits',
    'kpi.invoice.count': 'Total invoices count',
    'kpi.invoice.monthly_dist': 'Monthly distribution of invoices',
    'kpi.inflation.evolution': 'Average observed price evolution rate',
    'kpi.inflation.empty': 'Insufficient purchase data to calculate inflation.',
    'kpi.inflation.rise_pct': '+{percent}%',
    'kpi.inflation.drop_pct': '{percent}%',
    'kpi.taxes.total': 'Total accumulated VAT',
    'kpi.taxes.share': 'Share of taxes in your spending',
    'kpi.taxes.by_category': 'VAT paid by category',
    'kpi.taxes.by_store': 'VAT breakdown by store',
    'kpi.taxes.total_tva': 'Total VAT',
    'kpi.taxes.col.category': 'Category',
    'kpi.taxes.col.tax': 'VAT Paid',
    'kpi.taxes.col.share': 'Share',
    'kpi.taxes.col.store': 'Store',
    'kpi.productDetail.qty_purchased': 'Total Quantity Purchased',
    'kpi.productDetail.avg_price': 'Average Unit Price',
    'kpi.productDetail.purchases_count': 'Number of purchases analyzed',
    'kpi.productDetail.qty_axis': 'Volume (Quantity)',
    'kpi.productDetail.price_axis': 'Unit Price',
    'kpi.productDetail.qty_series': 'Consumed volume',
    'kpi.productDetail.price_series': 'Paid unit price',
    'kpi.productDetail.recent_purchases': 'Last 20 purchases of {product}',
    'kpi.productDetail.table.date': 'Date',
    'kpi.productDetail.table.store': 'Store',
    'kpi.productDetail.table.qty': 'Quantity',
    'kpi.productDetail.table.price': 'Unit Price',
    'kpi.productDetail.table.total': 'Total',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('fintrack_lang');
    return (saved === 'fr' || saved === 'en' ? saved : 'fr') as Language;
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('fintrack_lang', lang);
  };

  const t = (key: string): string => {
    const translation = translations[language][key];
    if (translation !== undefined) {
      return translation;
    }
    // Fallback: If translation key doesn't exist, return the key or guess key path
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
